CREATE TABLE public.ACTIVITY (
  ACTIVITY_REFID      UUID  NOT NULL PRIMARY KEY,
  TEACHER_ASSIGNMENT_REFID  UUID,
  STAFF_PERSONAL_REFID UUID,
  NUM_QUESTIONS      INT4,
  MAX_SCORE            INTEGER,
  MAX_TIME            INTEGER,
  CREATED_AT       TIMESTAMP    NOT NULL,
  UPDATED_AT       TIMESTAMP    NOT NULL
);

CREATE INDEX ACTIVITY_STAFF_REFID_IDX ON ACTIVITY USING btree(ACTIVITY_REFID , STAFF_PERSONAL_REFID);


CREATE TABLE public.STUDENT_SESSION (
  SESSION_REFID       UUID PRIMARY KEY,
  ACTIVITY_REFID      UUID  REFERENCES public.ACTIVITY (ACTIVITY_REFID) NOT NULL,
  STUDENT_PERSONAL_REFID  UUID  NOT NULL,
  STAFF_PERSONAL_REFID UUID  NOT NULL,
  NUM_ATTEMPTED      INT4 NOT NULL,
  SCORE            INT4  NOT NULL,
  SESSION_DURATION INTEGER,
  STATUS           VARCHAR(8),-- ORDINAL OF  NOT_STARTED(0)/IN_PROGRESS(1)/READY_FOR_SCORING(2)/SCORING_IN_PROGRESS(3)/COMPLETED(4)
  DT_STARTED      TIMESTAMP,
  DT_COMPLETED    TIMESTAMP,
  USER_AGENT      VARCHAR(250),
  CREATED_AT       TIMESTAMP    NOT NULL,
  UPDATED_AT       TIMESTAMP    NOT NULL
);

CREATE TABLE public.ITEM (
  ITEM_REFERENCE  VARCHAR(42) PRIMARY KEY,
  ORGANISATION_ID INT4,
  ITEM_POOL_ID    VARCHAR(60),
  TYPE  VARCHAR(36),
  CREATED_AT       TIMESTAMP    NOT NULL,
  UPDATED_AT       TIMESTAMP    NOT NULL
);

CREATE TABLE public.QUESTION (
  QUESTION_REFERENCE  VARCHAR(42) PRIMARY KEY,
  ITEM_REFERENCE VARCHAR(42)  REFERENCES public.ITEM (ITEM_REFERENCE) NOT NULL,
  RUBRIC_REFERENCE  VARCHAR(42),
  QUESTION_TYPE    VARCHAR(20),
  CREATED_AT       TIMESTAMP    NOT NULL,
  UPDATED_AT       TIMESTAMP    NOT NULL
);

CREATE TABLE public.SCORE (
  SCORE_REFERENCE  VARCHAR(42) PRIMARY KEY,
  ITEM_REFERENCE VARCHAR(42)  REFERENCES public.ITEM (ITEM_REFERENCE) NOT NULL,
  QUESTION_REFERENCE VARCHAR(42)  REFERENCES public.QUESTION (QUESTION_REFERENCE) NOT NULL,
  AUTOMARKABLE    BOOLEAN,
  CORRECT_RESPONSE  VARCHAR(40),
  CREATED_AT       TIMESTAMP    NOT NULL,
  UPDATED_AT       TIMESTAMP    NOT NULL
);

CREATE TABLE public.ACTIVITY_ITEM_SCORE (
  REFID 						BIGSERIAL             PRIMARY KEY,
  ACTIVITY_REFID      UUID  REFERENCES public.ACTIVITY (ACTIVITY_REFID) NOT NULL,
  ITEM_REFERENCE VARCHAR(42)  REFERENCES public.ITEM (ITEM_REFERENCE) NOT NULL,
  SCORE_REFERENCE VARCHAR(42)  REFERENCES public.SCORE (SCORE_REFERENCE) NOT NULL,
  MAX_SCORE INT4,
  WEIGHT INT4,
  CREATED_AT       TIMESTAMP    NOT NULL,
  UPDATED_AT       TIMESTAMP    NOT NULL
);


CREATE TABLE public.STUDENT_ITEM (
  REFID 						BIGSERIAL             PRIMARY KEY,
  SESSION_REFID UUID  REFERENCES public.STUDENT_SESSION (SESSION_REFID) NOT NULL,
  ITEM_REFERENCE VARCHAR(42)  REFERENCES public.ITEM (ITEM_REFERENCE) NOT NULL,
  TIME  INT4,
  MAX_SCORE INT4,
  USER_FLAGGED    BOOLEAN,
  CREATED_AT       TIMESTAMP    NOT NULL,
  UPDATED_AT       TIMESTAMP    NOT NULL
);


CREATE TABLE public.STUDENT_QUESTION (
  REFID 						BIGSERIAL             PRIMARY KEY,
  STUDENT_ITEM_REFID BIGINT  REFERENCES public.STUDENT_ITEM (REFID) NOT NULL,
  QUESTION_REFERENCE  VARCHAR(42)REFERENCES public.QUESTION (QUESTION_REFERENCE) NOT NULL,
  ACTUAL_RESPONSE    TEXT,
  CREATED_AT       TIMESTAMP    NOT NULL,
  UPDATED_AT       TIMESTAMP    NOT NULL
);

CREATE TABLE public.STUDENT_SCORE (
  RESPONSE_ID VARCHAR(80) PRIMARY KEY,
  SESSION_REFID UUID  REFERENCES public.STUDENT_SESSION (SESSION_REFID) NOT NULL,
  STUDENT_ITEM_REFID BIGINT  REFERENCES public.STUDENT_ITEM (REFID) NOT NULL,
  STUDENT_QUESTION_REFID  BIGINT REFERENCES public.STUDENT_QUESTION (REFID) NOT NULL,
  SCORE_REFERENCE  VARCHAR(42) REFERENCES public.SCORE (SCORE_REFERENCE),
  STAFF_PERSONAL_REFID  UUID, -- TEACHER WHO HAS ACTUAL SCORED
  ATTEMTED  BOOLEAN,
  VALUE TEXT,
  WEIGHT INT4,
  MAX_SCORE INT4,
  SCORE INT4,
  CREATED_AT       TIMESTAMP    NOT NULL,
  UPDATED_AT       TIMESTAMP    NOT NULL
);
