alter table public.QUESTION DROP COLUMN ITEM_REFERENCE;

alter table public.SCORE DROP COLUMN ITEM_REFERENCE;

alter table public.SCORE DROP COLUMN QUESTION_REFERENCE;

alter table public.ACTIVITY_ITEM_SCORE ADD COLUMN QUESTION_REFERENCE VARCHAR(42);



