alter table public.STUDENT_QUESTION ADD CONSTRAINT STUDENT_ITEM_QUESTION_UQ UNIQUE (STUDENT_ITEM_REFID, QUESTION_REFERENCE);
alter table public.STUDENT_ITEM ADD CONSTRAINT STUDENT_ITEM_UQ UNIQUE (SESSION_REFID, ITEM_REFERENCE);
